#define SECRET_SSID <"YOUR_WIFI_NETWORK_NAME">
#define SECRET_PASS <"YOUR_WIFI_PASSWORD">

#define SECRET_B_AUTH_TOKEN <"YOUR_BLYNK_AUTHENTICATION_TOKEN">

#define DATABASE_URL "YOUR_FIREBASE_DATABASE_URL"
#define DATABASE_SECRET "YOUR_FIREBASE_DATABASE_SECRET"